language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

cache:
  directories:
    - ./vendor

install:
  - php composer.phar install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry vendor/bin/coveralls -v
